
import '../styles/globals.css';
import Script from 'next/script';

export const metadata = {
  title: 'Testing app for NextInspect',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        {/* <div className='main'>
          <div className = "gradient"/>
        </div> */}
        <main>
          {children}
          <Script src='../../script.js' strategy='beforeInteractive/'/>
        </main>
        
      </body>
    </html>
  )
}
